modLoader = "javafml"
loaderVersion = "[1,)"

license = "UNLICENSED"

[[mods]]
modId = "loadingbackgrounds"
version = "${version}"

displayName = "Loading Backgrounds"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/loading-backgrounds"

authors = "lupiiin_, luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"
description = "Custom loading screen backgrounds."

logoFile = "assets/loadingbackgrounds/icon.png"

[[dependencies.loadingbackgrounds]]
modId = "forge"
mandatory = true
versionRange = "[51,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.loadingbackgrounds]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_min},${minecraft_version_max})"
ordering = "NONE"
side = "BOTH"
